# Generated by Django 4.0.3 on 2023-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название модели')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/models', verbose_name='Мини-изображение')),
                ('release_date', models.DateTimeField(verbose_name='Дата продажи')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='Доступно для продажи?')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Телефоны',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
